### ISSUE TITLE
Make exp work on Windows

### ISSUE THREAD

**Issue by ccheever** [exponentjs/exp#1]
It should work on Windows, but it doesn't yet.

The main issue is `child_process.spawn`, which will need to be changed in `exp` itself, `pm2`, and also `watchman` doesn't work.
`ngrok` may also require some modifications.

**Comment by ccheever** [comment]
@attilah suggested that this might help

http://danielpetisme.blogspot.hu/2015/01/fix-nodejs-spawingwindows.html

**Comment by jesseruder** [comment]
Fixed!
