### ISSUE TITLE
exp web does not work

### ISSUE THREAD

**Issue by harinij** [exponentjs/exp#22]
As per this page: http://www.reactnative.com/exponent-app-for-react-native-developers/

exp web --> command helps you run the an exponent app in the browser. However this command is not recognized as an option.

exp web
"web" is not an exp command. See "exp --help" for the full list of commands.

**Comment by ide** [comment]
That article is quite old and outdated, we don't support "exp web" anymore. Since then we've added Android support so most people can run Exponent projects on real devices now.

**Comment by harinij** [comment]
@ide Thanks for the reply. Is there any easy way to port a react native app build on exponent to web. Want to be able to view in on regular browser to publish as almost a react.js webpage. Or Anything that enable exp -> react native -> reactjs

**Comment by nikki93** [comment]
@harinin I think one way to do this is to share some code as libraries between a web page and an exponent app, but exponent itself doesn't provide a build tool for web things and I don't know if things that convert React Native apps to React DOM (for the web) would do a good job. You could use react-native-web to name components like `View` in your JSX and it would make `<div>` etc. underneath.

If you think about it, there are various elements like BlurView or different touch handling that would make the interface you design be different on the two platforms even in the design space (before you even code it). So I think starting with shared libraries and gradually sharing UI elements makes sense.

**Comment by harinij** [comment]
@nikki93 Thanks! Will look into it. Would have been great if exponent had a build tool to make this transition easier.

**Comment by nikki93** [comment]
@harinij It would! :) But I think unfortunately the problem is out of the scope of just a build tool if you use APIs like Geolocation and embedded Camera view etc. which we are trying to focus on bringing to JS. So right now we are prioritizing native.

create-react-app is a great tool for making a web build that you could try: https://github.com/facebookincubator/create-react-app
