### ISSUE TITLE
Can't install on linux

### ISSUE THREAD

**Issue by jlxw** [exponentjs/exp#3]
I tried building from the iojs default docker image, log is here:

https://registry.hub.docker.com/u/jlxw/exp/build_id/64718/code/bep2wfnxnnss8rrqfr6rwpg/

**Comment by jlxw** [comment]
I think the github issues can be resolved if we clone from https instead of ssh.

There is this error left for "git rev-list -n1 packager-root-fix":

npm ERR! git rev-list -n1 packager-root-fix: fatal: ambiguous argument 'packager-root-fix': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 packager-root-fix: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 packager-root-fix: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 packager-root-fix:

**Comment by ide** [comment]
The npm dependency is specified using npm's standard `<account>/<repo>#<branch>` syntax so you might want to try https://github.com/npm/npm/wiki/Troubleshooting#npm-only-uses-git-and-sshgit-urls-for-github-repos-breaking-proxies.

Just published a new version (0.7.2), which should fix the second issue.

**Comment by jlxw** [comment]
Works now! 
https://registry.hub.docker.com/u/jlxw/exp/build_id/64718/code/bnwxznvvdyftqgs4swrxtxv/

Did:
git config --global url."https://github.com/".insteadOf git@github.com:;\
git config --global url."https://".insteadOf git://;\
npm install -g exp

**Comment by ide** [comment]
Glad to hear that and thanks for the follow-up.
