### ISSUE TITLE
Not able to install exp on ubuntu 15.04!

### ISSUE THREAD

**Issue by danielmeneses** [exponentjs/exp#6]
Hi,

i'm trying to install exp, but i got the bellow errors, after typing "sudo npm install -g exp":
<pre>
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'ccheever/crayon' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'exp'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.19.0-26-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "exp"
npm ERR! cwd /home/danielmeneses
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/danielmeneses/npm-debug.log
npm ERR! not ok code 0

</pre>

Any help would be great!,
thanks

**Comment by ide** [comment]
You need to use a modern version of Node. Can you try io.js 2.5.0?

**Comment by danielmeneses** [comment]
Hi ide, thanks for the response,

so i did this:

$ nvm use iojs-v2.5.0
-> Now using io.js v2.5.0 (npm v2.13.2)

$ iojs -v
-> v2.5.0

$ node -v
-> v2.5.0

$ sudo npm i -g exp
->
<pre>
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'exponent/simple-spinner' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'exp'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.19.0-26-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "exp"
npm ERR! cwd /home/danielmeneses/dev/exp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/danielmeneses/dev/exp/npm-debug.logut 
npm ERR! not ok code 0
</pre>

something similar, but this time another package is missing from repo.
But i get what you're saying, maybe i've some messed path and npm is executing another node version.

**Comment by danielmeneses** [comment]
by the way:

$ npm -v
-> 2.13.2

**Comment by ide** [comment]
Your npm logs say `node -v v0.10.25`. Maybe the problem is with sudo -- you should almost never use sudo with npm.

**Comment by danielmeneses** [comment]
Yeap... your're right .. different versions between users, i've reclaimed ownership of npm commands and works ok!

thanks
