### ISSUE TITLE
Problem installing app on simulator: Error: Process exited with non-zero code: 69 (accepting Xcode license requires root access)

### ISSUE THREAD

**Issue by tomprogers** [exponentjs/exp#7]
This problem occurs when I click the "Install Exponent on Simulator" button in the Exponent GUI. The error is only visible in Electron's JS console. The simulator does not install, and I can't launch any apps. There is no other indication of a failure, not even in the console space where packaging status is reported.

Debugging reveals that the failure callback of `this._installAppInSimulatorAsync` (SimulatorControls.js:47) is being invoked. Digging through the `err` parameter with the dev tools reveals the problem:

"Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo."

Obv, Exp can't evade this requirement, but if there's a way to avoid swallowing the error message, that would be good. This failure case seems like it will strike enough people that Exp should watch for it specifically and react in a tailored way, perhaps by emitting a helpful statement in the packager's console.

**Edit**: I solved the problem by running Xcode once (from SmartSearch); I was presented with the license agreement immediately, with the standard pwd dialog. Exponent worked perfectly the next time I ran it.

**Comment by ccheever** [comment]
Hi @tomprogers-

Thanks for the report! I agree with your assessment of the issue. Feel free to submit a PR and I'll review it or we'll fix this when we get a chance. Sorry you encountered trouble. :(

**Comment by ccheever** [comment]
Added to trello

**Comment by tomprogers** [comment]
NP @ccheever : if I can figure out how to do the appropriate logging, I'll submit a PR.

**Comment by jesseruder** [comment]
This should be fixed now.
